config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  root to: 'users#index'
  resources :users
  resources :posts

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to posts_path, notice: "投稿「#{@post.comment}」を保存しました"
    else
      render :new
    end
  end

  def destroy
    set_post
    @post.destroy
    redirect_to posts_path, notice: "投稿「#{@post.comment}」を削除しました"
  end

  def show
    set_post
  end

  def edit
    set_post
  end

  def update
    @post = set_post

    if @post.update(post_params)
      redirect_to @post, notice: "投稿を「#{@post.comment}」更新しました"
    else
      render :edit, notice: "投稿の編集を失敗しました。"
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end
  def post_params
    params.require(:post).permit(:comment)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(uid: session_params[:uid])

    if @user&.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました。'
  end

  private
  def session_params
    params.require(:session).permit(:uid, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    set_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: "ユーザー「#{@user.uid}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    set_user
  end

  def update
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path, notice: "ユーザー「#{@user.uid}」更新しました。"
    else
      render :edit
    end
  end

  def destroy
    set_user
    @user.destroy
    redirect_to users_path, notice: "ユーザー「#{@user.uid}」を削除しました。"
  end

  private
  def user_params
    params.require(:user).permit(:uid, :password, :password_confirmation)
  end
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <li><%= link_to '投稿一覧', posts_path, class: 'nav-link' %></li>
        <% if current_user %>
          <li><%= link_to 'ログアウト', logout_url, method: :delete, class: 'nav-link' %></li>
          <li><%= link_to '新規投稿', new_post_path, class: 'nav-link' %></li>
        <% else %>
          <li><%= link_to 'ログイン', login_url, class: 'nav-link' %></li>
      <% end %>
      </ul>
    </header>
    <div class="container">
      <%if flash.notice.present? %>
        <div class="alert alert-success"><%= flash.notice %></div>
      <%end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <%= form_with model: post, local: true do |f| %>
    <div class="form-group">
      <%= f.label :comment%>
      <%= f.text_area :comment, class: 'form-control', rows: "2", id: 'post_title' %>
      <%= f.submit nil, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>編集</h1>

<%= render partial: 'form', locals: { post: @post} %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>

<ul>
  <li>
    <% @posts.each do |post| %>
      <%= post.user.uid %>
      <span>&nbsp;&nbsp;</span>
      <span>投稿日</span>
      <span><%= post.created_at.strftime("%Y/%m/%d")%></span>
      <br><%= link_to post.comment, post_path(post) %>
        <br><span>likeを追加</span>
            <br>
    <% end %>
  </li>
</ul>

app/views/posts/new.html.erb
<h1>新規投稿</h1>

<%= render partial: 'form', locals: { post: @post} %>

app/views/posts/show.html.erb
<h1>投稿</h1>
<p>ユーザーID：<%= @post.user.uid %></p>
<p>ツイート：<%= @post.comment %></p>

<%= link_to '削除', @post, method: :delete, data: {confirm: "ユーザー「#{@post.comment}」を削除します。よろしいですか？" }, class: 'btn btn-danger' %>

app/views/users/_form.html.erb
<%= form_for @user, url:  {action: :create} do |f| %>
  <div class="form-group">
    <%= f.label :uid, 'ユーザーID'%>
    <%= f.text_field :uid, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード'%>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）'%>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit '登録する', class: 'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー登録</h1>

<%= render partial: 'form', locals: { user: @user} %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<% @users.each do |user| %>
  <p>ユーザーID: <%= user.uid %>
    <%= link_to '削除', user, method: :delete, data: {confirm: "ユーザー「#{user.uid}」を削除します。よろしいですか？" }, class: 'btn btn-danger'  %>
  </p>
<% end %>
<%= link_to 'ユーザー登録', new_user_path, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>

<%= render partial: 'form', locals: { user: @user} %>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>

<%= @user.uid %>